markdown: redcarpet
title: Es muss sein!
tagline: 'Learning Bigdata'
decription: 'It`s a Jaehyun Lee`s blog to share knowledge about hpc system' 
author: 
name: 'Jayhyun Lee' 
url: http://xjayleex.github.io
highlighter: rouge
permalink: /:title

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
